<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Card'); ?>
<?php if ($_product->isSaleable()) :?>

    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <button type="button"
                        title="quickOrder"
                        class="action open primary tocart open-modal-form"
                        id="quick-order-button click"
                <span>Quick Order</span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>


<div class="popup-window" id="modal-form" style="display:none;">
    <p class="close">x</p>
        <input class="field-form" type="text" id="name_quick_order" placeholder="Name">
        <input class="field-form" type="text" id="phone_quick_order" placeholder="Phone">
        <input class="field-form" type="text" id="email_quick_order" placeholder="Email">
</div>

<script type="text/x-magento-init">
    {
        ".open-modal-form": {
            "ALevel_QuickOrder/js/quickorder": {}
        }
    }
</script>
